### ISSUE TITLE
Doesn't work for hipchat

### ISSUE THREAD

**Issue by MrMMorris** [hubot-scripts/hubot-mute#1]
Thanks for creating a super useful script!

I am trying to get it to work with hipchat, but although all the commands work, it doesn't seem to actually mute anything. 

I checked that the `message.room` doesn't have any prefix.

In 'test' room:

```
hubot mute list 
No channels have been muted yet

hubot mute test
test is muted

hello hubot
Well hello there, Marcus Morris
```

Any ideas?

cc'ing @michaelansel

**Comment by alexhouse** [comment]
Hmm, strange. Have you setup the `HUBOT_MUTE_ROOM_PREFIX` env? Does `hubot mute all` work?

What other hubot scripts have you got installed?

**Comment by MrMMorris** [comment]
I left `HUBOT_MUTE_ROOM_PREFIX` unset as I thought the default is blank. Do I need to explicitly `export HUBOT_MUTE_ROOM_PREFIX=` ?

**Comment by alexhouse** [comment]
I wouldn't have thought so, but try it just in case. I haven't looked at this for a while (and not at all with Hipchat) so if it doesn't work let me know and I'll have a proper look tomorrow when I get up!

**Comment by MrMMorris** [comment]
that worked! Not sure if you want to have it empty by default or not. The README _does_ say that `HUBOT_MUTE_ROOM_PREFIX` is required so that's my bad.

In my testing, I did encounter another issue. Seems `unmute all` doesn't work?:

```
hubot mute list
No channels have been muted yet

hubot mute test
Channel test muted

hubot unmute all
All channels have been unmuted

hubot mute test 
Channel test already muted

hubot mute list
test is muted

hubot unmute test
Channel test unmuted

hubot mute list
No channels have been muted yet
```

**Comment by alexhouse** [comment]
So the (un)mute all function doesn't list every channel - Hubot can never know every channel that he's connected in to as far as I know. Mute all is separate from the room list - you can mute individual channels, but then if you need to mute everything for some reason (big release, you want quiet across all channels/whatever) you can do that independently. Once all have been unmuted, the individual channel mutes will remain.

I guess I could change functionality to:
- `mute global` - mute everything
- `unmute global` - unmute everything
- `unmute all` - remove individual channel mutes

Might help clear that up?

**Comment by MrMMorris** [comment]
I think that would be lovely! Thanks for being so helpful :smile_cat:

**Comment by alexhouse** [comment]
0.0.6 has just been pushed to npmjs.com - global mute & unmute all have been implemented as above!

Please let me know if you have any further issues :)

**Comment by MrMMorris** [comment]
@alexhouse looks good! 

I have another request :smile: 

Can muted rooms be saved to the redis brain so they are still muted when I redeploy hubot?

**Comment by alexhouse** [comment]
Sure, I'll push another release tonight.
